#pragma once

// clang-format off

#define CONFIG_BRIGHTNESS_DEFAULT   (50)
#define CONFIG_BRIGHTNESS_DIMMED    (10)

#define CONFIG_DSP_BASS_MIN         (-6)
#define CONFIG_DSP_BASS_MAX         (6)
#define CONFIG_DSP_BASS_DEFAULT     (0)

#define CONFIG_DSP_TREBLE_MIN       (-6)
#define CONFIG_DSP_TREBLE_MAX       (6)
#define CONFIG_DSP_TREBLE_DEFAULT   (0)

#define CONFIG_BATTERY_LEVEL_FULL_MIN_THRESHOLD    (80)
#define CONFIG_BATTERY_LEVEL_HALF_MIN_THRESHOLD    (34)
#define CONFIG_BATTERY_LEVEL_LOW_MIN_THRESHOLD     (11)

#define CONFIG_STANDBY_TIMER_MINS_DEFAULT          (10)

#define CONFIG_MAX_AVRCP_VOLUME                    (127)

#if defined(MYND_RPI_MODIFICATION) && defined(HYBRID_VOLUME_MODE)
// Volume table in tasxxxx_volume_table.c supports -90 to +10 dB.
// 0 dB = unity gain (moderate). Positive dB = amplification (loud).
// Empirically: -27 dB ≈ barely audible, -12 dB ≈ comfortable, 0 dB ≈ loud.
#define CONFIG_HW_VOL_MIN_DB                       (-27)
#define CONFIG_HW_VOL_MAX_DB                       (10)
#define CONFIG_HW_VOL_STEP_AVRCP                   ((CONFIG_MAX_AVRCP_VOLUME * 1) / 100)    // 1% of 127
#define CONFIG_DEFAULT_ABSOLUTE_AVRCP_VOLUME       ((CONFIG_MAX_AVRCP_VOLUME * 80) / 100) // 80% of 127 avrcp max
#else
#define CONFIG_DEFAULT_ABSOLUTE_AVRCP_VOLUME       ((CONFIG_MAX_AVRCP_VOLUME * 40) / 100) // 40% of 127 avrcp max
#endif

#define CONFIG_IDLE_POWER_OFF_TIMEOUT_MS_FACTOR    (60UL * 1000UL)
#define CONFIG_MAX_IDLE_TIMEOUT_MINUTES            (254)
#define CONFIG_MIN_IDLE_TIMEOUT_MINUTES            (0)

#define CONFIG_CHARGE_OVER_TEMP_PROTECTION_DEGREE (45)
#define CONFIG_CHARGE_OVER_TEMP_PROTECTION_RECOVERY_DEGREE (40)
#define CONFIG_DISCHARGE_OVER_TEMP_PROTECTION_DEGREE (60)
#define CONFIG_DISCHARGE_OVER_TEMP_PROTECTION_RECOVERY_DEGREE (50)
#define CONFIG_CHARGE_UNDER_TEMP_PROTECTION_DEGREE (0)
#define CONFIG_CHARGE_UNDER_TEMP_PROTECTION_RECOVERY_DEGREE (5)
#define CONFIG_DISCHARGE_UNDER_TEMP_PROTECTION_DEGREE (-20)
#define CONFIG_DISCHARGE_UNDER_TEMP_PROTECTION_RECOVERY_DEGREE (-10)

#define CONFIG_POWER_BANK_LOW_BATTERY_THRESHOLD    (20)
#define CONFIG_POWER_BANK_LOW_BATTERY_RECOVERY_THRESHOLD (40)

#define CONFIG_FAST_CHARGE_DEFAULT (false)

// clang-format on
